import { type Genre, type Prompt } from '../types';

export const GENRES: Genre[] = [
  'slice-of-life',
  'coming-of-age',
  'horror',
  'fantasy',
  'sci-fi',
  'romance',
  'noir',
  'literary',
  'historical',
  'character',
];

export const prompts: Prompt[] = [
  // ── SLICE OF LIFE (20) ────────────────────────────────────────────────────
  {
    id: 'sol-001',
    genre: 'slice-of-life',
    text: 'Write the last hour of a Sunday before something changes.',
    difficulty: 'easy',
    tags: ['time', 'anticipation', 'quiet'],
  },
  {
    id: 'sol-002',
    genre: 'slice-of-life',
    text: 'Two people share a meal in a kitchen that belongs to neither of them.',
    difficulty: 'easy',
    tags: ['food', 'belonging', 'relationship'],
  },
  {
    id: 'sol-003',
    genre: 'slice-of-life',
    text: 'Write the commute home after the day went wrong in a way you can\'t explain to anyone.',
    difficulty: 'medium',
    tags: ['solitude', 'failure', 'transit'],
  },
  {
    id: 'sol-004',
    genre: 'slice-of-life',
    text: 'A woman sorts through her mother\'s belongings. She keeps one thing she has no use for.',
    difficulty: 'medium',
    tags: ['grief', 'objects', 'inheritance'],
  },
  {
    id: 'sol-005',
    genre: 'slice-of-life',
    text: 'Write a Tuesday in October with no plot. Just the texture of the day.',
    difficulty: 'hard',
    tags: ['atmosphere', 'season', 'mundane'],
  },
  {
    id: 'sol-006',
    genre: 'slice-of-life',
    text: 'Someone cancels plans they were looking forward to. Write why they\'re relieved.',
    difficulty: 'easy',
    tags: ['introversion', 'social', 'honesty'],
  },
  {
    id: 'sol-007',
    genre: 'slice-of-life',
    text: 'A small apartment, a power outage, two people who have been avoiding a conversation.',
    difficulty: 'medium',
    tags: ['confinement', 'avoidance', 'tension'],
  },
  {
    id: 'sol-008',
    genre: 'slice-of-life',
    text: 'Write the moment someone realizes the city they grew up in has become unrecognizable.',
    difficulty: 'medium',
    tags: ['place', 'change', 'nostalgia'],
  },
  {
    id: 'sol-009',
    genre: 'slice-of-life',
    text: 'A garage sale. One item that shouldn\'t be there. No one mentions it.',
    difficulty: 'hard',
    tags: ['secrets', 'objects', 'community'],
  },
  {
    id: 'sol-010',
    genre: 'slice-of-life',
    text: 'Write a friendship that is ending the way friendships end — gradually, without a scene.',
    difficulty: 'hard',
    tags: ['friendship', 'loss', 'drift'],
  },
  {
    id: 'sol-011',
    genre: 'slice-of-life',
    text: 'The last customer at a diner. The cook who wants to close. What they say, and what they don\'t.',
    difficulty: 'easy',
    tags: ['late night', 'strangers', 'ritual'],
  },
  {
    id: 'sol-012',
    genre: 'slice-of-life',
    text: 'Write someone who is very good at their job doing it one last time.',
    difficulty: 'medium',
    tags: ['work', 'expertise', 'ending'],
  },
  {
    id: 'sol-013',
    genre: 'slice-of-life',
    text: 'A waiting room where everyone is pretending to be fine.',
    difficulty: 'easy',
    tags: ['anxiety', 'public', 'performance'],
  },
  {
    id: 'sol-014',
    genre: 'slice-of-life',
    text: 'Write what it feels like to live somewhere you chose but don\'t love.',
    difficulty: 'medium',
    tags: ['place', 'regret', 'settling'],
  },
  {
    id: 'sol-015',
    genre: 'slice-of-life',
    text: 'Two siblings pack up a house. They have different memories of the same room.',
    difficulty: 'hard',
    tags: ['family', 'memory', 'objects'],
  },
  {
    id: 'sol-016',
    genre: 'slice-of-life',
    text: 'Write a party from the perspective of the person who can\'t wait for it to be over.',
    difficulty: 'easy',
    tags: ['social anxiety', 'crowd', 'endurance'],
  },
  {
    id: 'sol-017',
    genre: 'slice-of-life',
    text: 'A morning routine, written as evidence of a life.',
    difficulty: 'hard',
    tags: ['habit', 'ritual', 'character'],
  },
  {
    id: 'sol-018',
    genre: 'slice-of-life',
    text: 'Someone overhears a conversation that changes how they understand their own past.',
    difficulty: 'medium',
    tags: ['revelation', 'eavesdropping', 'reframing'],
  },
  {
    id: 'sol-019',
    genre: 'slice-of-life',
    text: 'Write the day before something good happens, when no one knows it yet.',
    difficulty: 'easy',
    tags: ['anticipation', 'unknowing', 'ordinary'],
  },
  {
    id: 'sol-020',
    genre: 'slice-of-life',
    text: 'A walk home that takes longer than it should. Write what keeps interrupting it.',
    difficulty: 'medium',
    tags: ['urban', 'delay', 'observation'],
  },

  // ── COMING OF AGE (15) ───────────────────────────────────────────────────
  {
    id: 'coa-001',
    genre: 'coming-of-age',
    text: 'Write the moment someone realizes they are no longer who they used to be.',
    difficulty: 'medium',
    tags: ['identity', 'change', 'recognition'],
  },
  {
    id: 'coa-002',
    genre: 'coming-of-age',
    text: 'The summer something went wrong that was never spoken about again.',
    difficulty: 'medium',
    tags: ['summer', 'silence', 'family'],
  },
  {
    id: 'coa-003',
    genre: 'coming-of-age',
    text: 'Write the first time someone understood that adults were making it up as they went.',
    difficulty: 'easy',
    tags: ['disillusionment', 'authority', 'epiphany'],
  },
  {
    id: 'coa-004',
    genre: 'coming-of-age',
    text: 'A friendship that couldn\'t survive one of them becoming someone different.',
    difficulty: 'hard',
    tags: ['friendship', 'change', 'loss'],
  },
  {
    id: 'coa-005',
    genre: 'coming-of-age',
    text: 'Write the embarrassment that still hasn\'t fully left, years later.',
    difficulty: 'easy',
    tags: ['humiliation', 'memory', 'body'],
  },
  {
    id: 'coa-006',
    genre: 'coming-of-age',
    text: 'The year someone started lying about small things and couldn\'t stop.',
    difficulty: 'medium',
    tags: ['deception', 'habit', 'adolescence'],
  },
  {
    id: 'coa-007',
    genre: 'coming-of-age',
    text: 'Write the specific ache of wanting to leave and being terrified to go.',
    difficulty: 'hard',
    tags: ['ambition', 'fear', 'home'],
  },
  {
    id: 'coa-008',
    genre: 'coming-of-age',
    text: 'A mentor who turned out to be something less than what they seemed.',
    difficulty: 'medium',
    tags: ['admiration', 'disillusionment', 'trust'],
  },
  {
    id: 'coa-009',
    genre: 'coming-of-age',
    text: 'Write the first time someone chose themselves and it cost them something real.',
    difficulty: 'hard',
    tags: ['selfhood', 'cost', 'agency'],
  },
  {
    id: 'coa-010',
    genre: 'coming-of-age',
    text: 'A bedroom at sixteen. The things on the walls. What they meant.',
    difficulty: 'easy',
    tags: ['objects', 'identity', 'adolescence'],
  },
  {
    id: 'coa-011',
    genre: 'coming-of-age',
    text: 'Write the last night of something — summer job, school year, relationship — before it became the past.',
    difficulty: 'medium',
    tags: ['endings', 'nostalgia', 'transition'],
  },
  {
    id: 'coa-012',
    genre: 'coming-of-age',
    text: 'Someone overhears their parents fighting for the first time and understands that the marriage is a performance.',
    difficulty: 'hard',
    tags: ['family', 'revelation', 'disillusionment'],
  },
  {
    id: 'coa-013',
    genre: 'coming-of-age',
    text: 'The longing you couldn\'t name yet. Write it from the outside.',
    difficulty: 'hard',
    tags: ['desire', 'confusion', 'youth'],
  },
  {
    id: 'coa-014',
    genre: 'coming-of-age',
    text: 'Write the day a young person becomes ashamed of their family for the first time.',
    difficulty: 'medium',
    tags: ['class', 'shame', 'identity'],
  },
  {
    id: 'coa-015',
    genre: 'coming-of-age',
    text: 'A graduation speech that says everything except what the speaker actually means.',
    difficulty: 'medium',
    tags: ['ceremony', 'subtext', 'performance'],
  },

  // ── HORROR (15) ──────────────────────────────────────────────────────────
  {
    id: 'hor-001',
    genre: 'horror',
    text: 'Something in the house has always made that sound. Tonight you finally look.',
    difficulty: 'easy',
    tags: ['domestic', 'dread', 'the unknown'],
  },
  {
    id: 'hor-002',
    genre: 'horror',
    text: 'Write the moment a character realizes the rules of the place they\'re in have been wrong from the start.',
    difficulty: 'hard',
    tags: ['gaslighting', 'wrongness', 'revelation'],
  },
  {
    id: 'hor-003',
    genre: 'horror',
    text: 'A woman begins to suspect that her neighbor knows something she doesn\'t. She\'s right.',
    difficulty: 'medium',
    tags: ['paranoia', 'community', 'knowledge'],
  },
  {
    id: 'hor-004',
    genre: 'horror',
    text: 'Write the day before the town went wrong, from the perspective of someone who thought everything was fine.',
    difficulty: 'medium',
    tags: ['obliviousness', 'community', 'dramatic irony'],
  },
  {
    id: 'hor-005',
    genre: 'horror',
    text: 'The new hire at the office is too good. Too eager. Too prepared. Write the week they arrived.',
    difficulty: 'medium',
    tags: ['workplace', 'uncanny', 'social horror'],
  },
  {
    id: 'hor-006',
    genre: 'horror',
    text: 'Write what the house looked like from the outside to the family that moved in after.',
    difficulty: 'hard',
    tags: ['aftermath', 'witness', 'place'],
  },
  {
    id: 'hor-007',
    genre: 'horror',
    text: 'A child tells their parent about the friend who visits at night. The parent listens this time.',
    difficulty: 'easy',
    tags: ['children', 'belief', 'parent'],
  },
  {
    id: 'hor-008',
    genre: 'horror',
    text: 'Write the thing that\'s been following you — not as a monster, but as an obligation.',
    difficulty: 'hard',
    tags: ['metaphor', 'burden', 'pursuit'],
  },
  {
    id: 'hor-009',
    genre: 'horror',
    text: 'The photograph from twenty years ago has one person in it who wasn\'t there.',
    difficulty: 'easy',
    tags: ['time', 'images', 'intrusion'],
  },
  {
    id: 'hor-010',
    genre: 'horror',
    text: 'Write the moment a character recognizes that what they\'ve been afraid of is already inside the house.',
    difficulty: 'medium',
    tags: ['safety', 'violation', 'domestic'],
  },
  {
    id: 'hor-011',
    genre: 'horror',
    text: 'A town that requires one thing of its residents. Most of them have stopped questioning why.',
    difficulty: 'hard',
    tags: ['community', 'ritual', 'compliance'],
  },
  {
    id: 'hor-012',
    genre: 'horror',
    text: 'Write grief as a physical presence. Not a metaphor — an entity in the house.',
    difficulty: 'medium',
    tags: ['grief', 'embodiment', 'haunting'],
  },
  {
    id: 'hor-013',
    genre: 'horror',
    text: 'The last voicemail from someone who is no longer reachable. What it said.',
    difficulty: 'easy',
    tags: ['technology', 'absence', 'voice'],
  },
  {
    id: 'hor-014',
    genre: 'horror',
    text: 'Write the dream that keeps coming back differently, except for the one detail that never changes.',
    difficulty: 'hard',
    tags: ['recurring dream', 'fixation', 'psychological'],
  },
  {
    id: 'hor-015',
    genre: 'horror',
    text: 'A road that people who grew up here know not to take after dark. Someone new just moved in.',
    difficulty: 'easy',
    tags: ['local knowledge', 'stranger', 'folklore'],
  },

  // ── FANTASY (15) ─────────────────────────────────────────────────────────
  {
    id: 'fan-001',
    genre: 'fantasy',
    text: 'Write the first law of a magic system from the perspective of someone who broke it.',
    difficulty: 'medium',
    tags: ['magic', 'rules', 'transgression'],
  },
  {
    id: 'fan-002',
    genre: 'fantasy',
    text: 'A cartographer is commissioned to map a territory that doesn\'t exist yet.',
    difficulty: 'medium',
    tags: ['creation', 'maps', 'power'],
  },
  {
    id: 'fan-003',
    genre: 'fantasy',
    text: 'Write the last night of a kingdom that had, for a century, been at peace.',
    difficulty: 'hard',
    tags: ['endings', 'peace', 'empire'],
  },
  {
    id: 'fan-004',
    genre: 'fantasy',
    text: 'A god who has grown bored with being worshipped goes unrecognized for the first time.',
    difficulty: 'hard',
    tags: ['divinity', 'ego', 'anonymity'],
  },
  {
    id: 'fan-005',
    genre: 'fantasy',
    text: 'Write the healer in a world of warriors — what they know that no one else does.',
    difficulty: 'medium',
    tags: ['knowledge', 'war', 'perspective'],
  },
  {
    id: 'fan-006',
    genre: 'fantasy',
    text: 'The chosen one refuses. Write the conversation with whoever did the choosing.',
    difficulty: 'easy',
    tags: ['subversion', 'prophecy', 'refusal'],
  },
  {
    id: 'fan-007',
    genre: 'fantasy',
    text: 'A fable about a creature that traded its shadow for something it wanted. Was it worth it?',
    difficulty: 'easy',
    tags: ['fable', 'trade', 'consequence'],
  },
  {
    id: 'fan-008',
    genre: 'fantasy',
    text: 'Write a spell that requires something the caster cannot get back.',
    difficulty: 'medium',
    tags: ['sacrifice', 'magic cost', 'loss'],
  },
  {
    id: 'fan-009',
    genre: 'fantasy',
    text: 'Two ancient enemies meet in a tavern and order the same drink.',
    difficulty: 'easy',
    tags: ['enemies', 'humanity', 'irony'],
  },
  {
    id: 'fan-010',
    genre: 'fantasy',
    text: 'Write the story told in a world where stories are currency — and someone spent their last one.',
    difficulty: 'hard',
    tags: ['stories', 'value', 'loss'],
  },
  {
    id: 'fan-011',
    genre: 'fantasy',
    text: 'The dragon who has kept its hoard for five hundred years has finally found something it cannot keep.',
    difficulty: 'medium',
    tags: ['dragon', 'possession', 'change'],
  },
  {
    id: 'fan-012',
    genre: 'fantasy',
    text: 'Write a market in a city where memories are bought and sold.',
    difficulty: 'hard',
    tags: ['memory', 'economy', 'ethics'],
  },
  {
    id: 'fan-013',
    genre: 'fantasy',
    text: 'A sword that cannot be unsheathed without blood. Write the day its owner decides to never use it again.',
    difficulty: 'medium',
    tags: ['weapon', 'pacifism', 'oath'],
  },
  {
    id: 'fan-014',
    genre: 'fantasy',
    text: 'Write the witch who no longer takes clients. Someone knocks anyway.',
    difficulty: 'easy',
    tags: ['retirement', 'witch', 'disruption'],
  },
  {
    id: 'fan-015',
    genre: 'fantasy',
    text: 'The stars have names. One of them has stopped answering.',
    difficulty: 'hard',
    tags: ['mythology', 'silence', 'loss'],
  },

  // ── SCI-FI (10) ──────────────────────────────────────────────────────────
  {
    id: 'sci-001',
    genre: 'sci-fi',
    text: 'A woman receives a message from a version of herself she doesn\'t remember being.',
    difficulty: 'medium',
    tags: ['time', 'identity', 'communication'],
  },
  {
    id: 'sci-002',
    genre: 'sci-fi',
    text: 'Write the first generation born on a colony ship who will never see Earth.',
    difficulty: 'medium',
    tags: ['diaspora', 'home', 'identity'],
  },
  {
    id: 'sci-003',
    genre: 'sci-fi',
    text: 'The last human who refuses to be uploaded. Write the day they explain why.',
    difficulty: 'hard',
    tags: ['transhumanism', 'body', 'refusal'],
  },
  {
    id: 'sci-004',
    genre: 'sci-fi',
    text: 'Two AIs argue about whether either of them is conscious. Neither wins.',
    difficulty: 'hard',
    tags: ['consciousness', 'AI', 'philosophy'],
  },
  {
    id: 'sci-005',
    genre: 'sci-fi',
    text: 'Write the quiet bureaucracy of first contact — the forms, the protocols, the waiting.',
    difficulty: 'medium',
    tags: ['first contact', 'bureaucracy', 'mundane'],
  },
  {
    id: 'sci-006',
    genre: 'sci-fi',
    text: 'A scientist who has spent thirty years on a project that might not be real anymore.',
    difficulty: 'hard',
    tags: ['obsession', 'obsolescence', 'science'],
  },
  {
    id: 'sci-007',
    genre: 'sci-fi',
    text: 'The cure exists. Write the meeting where they decide who doesn\'t get it.',
    difficulty: 'hard',
    tags: ['medicine', 'ethics', 'scarcity'],
  },
  {
    id: 'sci-008',
    genre: 'sci-fi',
    text: 'Write a city where memory is regulated. Someone remembers too much.',
    difficulty: 'medium',
    tags: ['memory', 'control', 'rebellion'],
  },
  {
    id: 'sci-009',
    genre: 'sci-fi',
    text: 'The terraforming worked. Write the first spring.',
    difficulty: 'easy',
    tags: ['terraforming', 'nature', 'beginning'],
  },
  {
    id: 'sci-010',
    genre: 'sci-fi',
    text: 'A maintenance worker on a space station overhears something they weren\'t meant to.',
    difficulty: 'easy',
    tags: ['class', 'labor', 'secrets'],
  },

  // ── ROMANCE (10) ─────────────────────────────────────────────────────────
  {
    id: 'rom-001',
    genre: 'romance',
    text: 'Two people who almost were something, years later, in the same room.',
    difficulty: 'medium',
    tags: ['reunion', 'almost', 'history'],
  },
  {
    id: 'rom-002',
    genre: 'romance',
    text: 'Write the moment just before someone says something they can\'t take back.',
    difficulty: 'medium',
    tags: ['anticipation', 'confession', 'risk'],
  },
  {
    id: 'rom-003',
    genre: 'romance',
    text: 'A love that was real but came at the wrong time. Write the right time, imagined.',
    difficulty: 'hard',
    tags: ['timing', 'counterfactual', 'longing'],
  },
  {
    id: 'rom-004',
    genre: 'romance',
    text: 'Write the restraint. What wasn\'t said, what wasn\'t touched, and why.',
    difficulty: 'hard',
    tags: ['restraint', 'tension', 'subtext'],
  },
  {
    id: 'rom-005',
    genre: 'romance',
    text: 'Two people share a long car ride. They don\'t talk about what\'s happening between them.',
    difficulty: 'medium',
    tags: ['confinement', 'avoidance', 'tension'],
  },
  {
    id: 'rom-006',
    genre: 'romance',
    text: 'Write the specific thing about a person that you know you\'ll miss most. Not the grand things.',
    difficulty: 'easy',
    tags: ['detail', 'loss', 'love'],
  },
  {
    id: 'rom-007',
    genre: 'romance',
    text: 'The letter they wrote but never sent. Found, years later, by someone else.',
    difficulty: 'medium',
    tags: ['letters', 'time', 'discovery'],
  },
  {
    id: 'rom-008',
    genre: 'romance',
    text: 'Write the end of a relationship from the moment it became inevitable — not the fight, but the quiet before.',
    difficulty: 'hard',
    tags: ['endings', 'inevitability', 'quiet'],
  },
  {
    id: 'rom-009',
    genre: 'romance',
    text: 'Two people who have always disliked each other are forced to share one good day.',
    difficulty: 'easy',
    tags: ['forced proximity', 'dislike', 'change'],
  },
  {
    id: 'rom-010',
    genre: 'romance',
    text: 'Write what it feels like to choose someone. Not fall for them — choose them, on an ordinary day.',
    difficulty: 'medium',
    tags: ['choice', 'commitment', 'ordinary'],
  },

  // ── NOIR (10) ────────────────────────────────────────────────────────────
  {
    id: 'noi-001',
    genre: 'noir',
    text: 'Write the last night a detective believes in anything.',
    difficulty: 'medium',
    tags: ['disillusionment', 'detective', 'faith'],
  },
  {
    id: 'noi-002',
    genre: 'noir',
    text: 'The client was lying. Write the moment the investigator decided to keep working anyway.',
    difficulty: 'medium',
    tags: ['deceit', 'complicity', 'choice'],
  },
  {
    id: 'noi-003',
    genre: 'noir',
    text: 'A city at 3 a.m., described as if it has always looked like this and always will.',
    difficulty: 'easy',
    tags: ['atmosphere', 'city', 'late night'],
  },
  {
    id: 'noi-004',
    genre: 'noir',
    text: 'Write the alibi. Make it almost true.',
    difficulty: 'easy',
    tags: ['deception', 'crime', 'voice'],
  },
  {
    id: 'noi-005',
    genre: 'noir',
    text: 'The wrong person got away. Write the day the investigator stopped being surprised by this.',
    difficulty: 'hard',
    tags: ['injustice', 'cynicism', 'acceptance'],
  },
  {
    id: 'noi-006',
    genre: 'noir',
    text: 'Write a character who does the right thing and pays for it in the exact coin the genre demands.',
    difficulty: 'hard',
    tags: ['moral cost', 'genre', 'consequence'],
  },
  {
    id: 'noi-007',
    genre: 'noir',
    text: 'Someone returns to the city they were run out of. Write the first hour back.',
    difficulty: 'medium',
    tags: ['return', 'history', 'tension'],
  },
  {
    id: 'noi-008',
    genre: 'noir',
    text: 'A poker game with one hand left. Write what everyone in the room already knows.',
    difficulty: 'medium',
    tags: ['cards', 'subtext', 'stakes'],
  },
  {
    id: 'noi-009',
    genre: 'noir',
    text: 'The witness who won\'t talk knows more than the killer. Write the interview.',
    difficulty: 'hard',
    tags: ['witness', 'secrets', 'power'],
  },
  {
    id: 'noi-010',
    genre: 'noir',
    text: 'Write a double-cross from the perspective of the one being crossed.',
    difficulty: 'medium',
    tags: ['betrayal', 'realization', 'voice'],
  },

  // ── LITERARY / EXPERIMENTAL (10) ─────────────────────────────────────────
  {
    id: 'lit-001',
    genre: 'literary',
    text: 'Write a story told entirely in the second person where "you" is the wrong person.',
    difficulty: 'hard',
    tags: ['second person', 'form', 'distance'],
  },
  {
    id: 'lit-002',
    genre: 'literary',
    text: 'Tell the same moment from three perspectives. In the third, we learn the first two were lying.',
    difficulty: 'hard',
    tags: ['unreliable narrator', 'perspective', 'truth'],
  },
  {
    id: 'lit-003',
    genre: 'literary',
    text: 'Write a story in which the white space on the page is as important as the words.',
    difficulty: 'hard',
    tags: ['form', 'silence', 'absence'],
  },
  {
    id: 'lit-004',
    genre: 'literary',
    text: 'A character who cannot stop telling the truth, in a world that rewards comfortable lies.',
    difficulty: 'medium',
    tags: ['honesty', 'alienation', 'society'],
  },
  {
    id: 'lit-005',
    genre: 'literary',
    text: 'Write a love story in which no one says the word love and it is more present for it.',
    difficulty: 'hard',
    tags: ['restraint', 'implication', 'form'],
  },
  {
    id: 'lit-006',
    genre: 'literary',
    text: 'A list of things a woman owns. Through the list, we understand everything about her life.',
    difficulty: 'medium',
    tags: ['form', 'objects', 'character'],
  },
  {
    id: 'lit-007',
    genre: 'literary',
    text: 'Write a story from the perspective of a place watching people move through it.',
    difficulty: 'medium',
    tags: ['place', 'point of view', 'witness'],
  },
  {
    id: 'lit-008',
    genre: 'literary',
    text: 'A man writes letters to someone who has never existed and finds they write back.',
    difficulty: 'hard',
    tags: ['imagination', 'loneliness', 'form'],
  },
  {
    id: 'lit-009',
    genre: 'literary',
    text: 'Write a story in which the most important thing is the sentence that never gets written.',
    difficulty: 'hard',
    tags: ['absence', 'failure', 'writing'],
  },
  {
    id: 'lit-010',
    genre: 'literary',
    text: 'A translation that changes the meaning of something. Write both versions.',
    difficulty: 'medium',
    tags: ['language', 'interpretation', 'meaning'],
  },

  // ── HISTORICAL FICTION (8) ───────────────────────────────────────────────
  {
    id: 'his-001',
    genre: 'historical',
    text: 'A soldier writes a letter home that he will never send.',
    difficulty: 'easy',
    tags: ['war', 'letters', 'silence'],
  },
  {
    id: 'his-002',
    genre: 'historical',
    text: 'Write the day a woman in a particular century realizes the rules were not made with her in mind.',
    difficulty: 'medium',
    tags: ['gender', 'power', 'recognition'],
  },
  {
    id: 'his-003',
    genre: 'historical',
    text: 'The night before a revolution, a cook in the palace prepares the same meal as always.',
    difficulty: 'hard',
    tags: ['ordinary', 'upheaval', 'oblivion'],
  },
  {
    id: 'his-004',
    genre: 'historical',
    text: 'Write the crossing — a ship, a century, a person who didn\'t have a choice.',
    difficulty: 'medium',
    tags: ['migration', 'displacement', 'body'],
  },
  {
    id: 'his-005',
    genre: 'historical',
    text: 'An artisan in a dying trade makes one last perfect thing and knows no one will care.',
    difficulty: 'hard',
    tags: ['craft', 'obsolescence', 'pride'],
  },
  {
    id: 'his-006',
    genre: 'historical',
    text: 'Two people on opposite sides of a conflict meet in a place the war hasn\'t reached yet.',
    difficulty: 'medium',
    tags: ['war', 'humanity', 'neutrality'],
  },
  {
    id: 'his-007',
    genre: 'historical',
    text: 'Write the market day in a town that will not exist in fifty years.',
    difficulty: 'easy',
    tags: ['place', 'ordinary', 'erasure'],
  },
  {
    id: 'his-008',
    genre: 'historical',
    text: 'A woman learns to read in secret. Write what the first page says.',
    difficulty: 'easy',
    tags: ['literacy', 'freedom', 'secrecy'],
  },

  // ── CHARACTER STUDIES (7) ────────────────────────────────────────────────
  {
    id: 'cha-001',
    genre: 'character',
    text: 'Write a character who is exactly who they say they are. Make it terrifying.',
    difficulty: 'hard',
    tags: ['honesty', 'menace', 'subversion'],
  },
  {
    id: 'cha-002',
    genre: 'character',
    text: 'A man who has lived the same day for thirty years. No time loop — just habit. Write a Tuesday.',
    difficulty: 'medium',
    tags: ['routine', 'stasis', 'ordinary'],
  },
  {
    id: 'cha-003',
    genre: 'character',
    text: 'Write a character whose kindness is the most frightening thing about them.',
    difficulty: 'hard',
    tags: ['kindness', 'menace', 'motivation'],
  },
  {
    id: 'cha-004',
    genre: 'character',
    text: 'Someone who built their entire life around a belief that turned out to be wrong. It\'s Tuesday. They\'re fine.',
    difficulty: 'hard',
    tags: ['belief', 'collapse', 'resilience'],
  },
  {
    id: 'cha-005',
    genre: 'character',
    text: 'Write the person everyone in town has an opinion about. Let them be silent.',
    difficulty: 'medium',
    tags: ['reputation', 'silence', 'judgment'],
  },
  {
    id: 'cha-006',
    genre: 'character',
    text: 'A character who lies to themselves about one thing and is scrupulously honest about everything else.',
    difficulty: 'medium',
    tags: ['self-deception', 'contradiction', 'character'],
  },
  {
    id: 'cha-007',
    genre: 'character',
    text: 'Write the villain\'s ordinary morning. Make it mundane. Make it worse for it.',
    difficulty: 'easy',
    tags: ['villain', 'mundane', 'normalcy'],
  },
];
