import { type Genre, type Prompt } from '../types';

export const GENRES: Genre[] = [
  'Slice of Life',
  'Coming of Age',
  'Horror',
  'Fantasy',
  'Sci-Fi',
  'Romance',
  'Crime / Noir',
  'Literary / Experimental',
  'Historical Fiction',
  'Character Studies',
];

export const prompts: Prompt[] = [

  // ─── SLICE OF LIFE (20) ────────────────────────────────────────────────────

  {
    id: 'sol-01',
    genre: 'Slice of Life',
    text: 'Write the last hour of a Sunday before something changes. Don\'t say what changes.',
    difficulty: 'easy',
    tags: ['quiet', 'anticipation', 'domestic'],
  },
  {
    id: 'sol-02',
    genre: 'Slice of Life',
    text: 'Two coworkers eat lunch together every day and have never once talked about anything real.',
    difficulty: 'easy',
    tags: ['routine', 'distance', 'workplace'],
  },
  {
    id: 'sol-03',
    genre: 'Slice of Life',
    text: 'Write a person\'s entire relationship with a piece of furniture they\'re about to throw away.',
    difficulty: 'medium',
    tags: ['memory', 'objects', 'time'],
  },
  {
    id: 'sol-04',
    genre: 'Slice of Life',
    text: 'Someone makes the same meal their mother made. They get the recipe slightly wrong every time on purpose.',
    difficulty: 'easy',
    tags: ['family', 'grief', 'ritual'],
  },
  {
    id: 'sol-05',
    genre: 'Slice of Life',
    text: 'Write the drive home after a party where you didn\'t know anyone and pretended otherwise.',
    difficulty: 'easy',
    tags: ['loneliness', 'performance', 'night'],
  },
  {
    id: 'sol-06',
    genre: 'Slice of Life',
    text: 'A neighborhood changes over twenty years, told through the same window.',
    difficulty: 'medium',
    tags: ['place', 'time', 'change'],
  },
  {
    id: 'sol-07',
    genre: 'Slice of Life',
    text: 'Write the morning after a phone call that didn\'t go the way you planned.',
    difficulty: 'easy',
    tags: ['aftermath', 'silence', 'domestic'],
  },
  {
    id: 'sol-08',
    genre: 'Slice of Life',
    text: 'Two siblings clean out their parents\' house. They keep stopping to argue about what things meant.',
    difficulty: 'medium',
    tags: ['family', 'objects', 'grief'],
  },
  {
    id: 'sol-09',
    genre: 'Slice of Life',
    text: 'Someone is very good at their job and increasingly certain it doesn\'t matter.',
    difficulty: 'medium',
    tags: ['work', 'meaning', 'drift'],
  },
  {
    id: 'sol-10',
    genre: 'Slice of Life',
    text: 'Write a friendship that exists only in one specific context — a bar, a carpool, a weekly class — and what happens when that context disappears.',
    difficulty: 'medium',
    tags: ['friendship', 'circumstance', 'ending'],
  },
  {
    id: 'sol-11',
    genre: 'Slice of Life',
    text: 'A person eats alone at a restaurant they used to go to with someone else.',
    difficulty: 'easy',
    tags: ['loss', 'place', 'memory'],
  },
  {
    id: 'sol-12',
    genre: 'Slice of Life',
    text: 'Write the specific texture of a town you can\'t wait to leave but will probably miss.',
    difficulty: 'easy',
    tags: ['place', 'ambivalence', 'home'],
  },
  {
    id: 'sol-13',
    genre: 'Slice of Life',
    text: 'Someone teaches their parent how to use something they used to need help with themselves.',
    difficulty: 'easy',
    tags: ['family', 'time', 'reversal'],
  },
  {
    id: 'sol-14',
    genre: 'Slice of Life',
    text: 'Write the last day of a job before moving on. Nothing dramatic happens.',
    difficulty: 'easy',
    tags: ['transition', 'work', 'ordinary'],
  },
  {
    id: 'sol-15',
    genre: 'Slice of Life',
    text: 'A couple runs the same errand they\'ve run together for fifteen years. Something is different today and neither mentions it.',
    difficulty: 'medium',
    tags: ['relationship', 'tension', 'routine'],
  },
  {
    id: 'sol-16',
    genre: 'Slice of Life',
    text: 'Write a summer afternoon from the perspective of someone who knows it\'s the last one like it.',
    difficulty: 'easy',
    tags: ['summer', 'endings', 'awareness'],
  },
  {
    id: 'sol-17',
    genre: 'Slice of Life',
    text: 'Someone finds an old voicemail they never deleted. They\'ve listened to it so many times they\'ve memorized it.',
    difficulty: 'easy',
    tags: ['memory', 'grief', 'technology'],
  },
  {
    id: 'sol-18',
    genre: 'Slice of Life',
    text: 'Write a birthday that no one forgot but everyone handled wrong.',
    difficulty: 'easy',
    tags: ['family', 'disappointment', 'connection'],
  },
  {
    id: 'sol-19',
    genre: 'Slice of Life',
    text: 'Two neighbors who have never spoken finally do. Write only their dialogue.',
    difficulty: 'easy',
    tags: ['dialogue', 'strangers', 'proximity'],
  },
  {
    id: 'sol-20',
    genre: 'Slice of Life',
    text: 'Write the year after something good ended. Not in grief — just in the ordinary rearranging that follows.',
    difficulty: 'medium',
    tags: ['aftermath', 'adjustment', 'time'],
  },

  // ─── COMING OF AGE (15) ───────────────────────────────────────────────────

  {
    id: 'coa-01',
    genre: 'Coming of Age',
    text: 'Write the moment someone realizes they are no longer who they used to be — and can\'t tell if that\'s a loss.',
    difficulty: 'medium',
    tags: ['identity', 'change', 'awareness'],
  },
  {
    id: 'coa-02',
    genre: 'Coming of Age',
    text: 'A teenager overhears something about their parents that reorders everything.',
    difficulty: 'easy',
    tags: ['family', 'revelation', 'childhood'],
  },
  {
    id: 'coa-03',
    genre: 'Coming of Age',
    text: 'Write the summer a friendship became something more, and then nothing at all.',
    difficulty: 'medium',
    tags: ['friendship', 'romance', 'summer', 'loss'],
  },
  {
    id: 'coa-04',
    genre: 'Coming of Age',
    text: 'Someone performs a version of themselves at a new school for so long they forget which parts were real.',
    difficulty: 'medium',
    tags: ['identity', 'performance', 'school'],
  },
  {
    id: 'coa-05',
    genre: 'Coming of Age',
    text: 'Write a first job through the lens of everything it quietly taught.',
    difficulty: 'easy',
    tags: ['work', 'youth', 'learning'],
  },
  {
    id: 'coa-06',
    genre: 'Coming of Age',
    text: 'The last night before leaving for college. No one knows what to say, so no one says much.',
    difficulty: 'easy',
    tags: ['departure', 'family', 'endings'],
  },
  {
    id: 'coa-07',
    genre: 'Coming of Age',
    text: 'Write the specific embarrassment of wanting something you weren\'t supposed to want yet.',
    difficulty: 'medium',
    tags: ['desire', 'shame', 'youth'],
  },
  {
    id: 'coa-08',
    genre: 'Coming of Age',
    text: 'A kid realizes that one of their parents is wrong about something important. They don\'t say anything.',
    difficulty: 'medium',
    tags: ['family', 'disillusionment', 'silence'],
  },
  {
    id: 'coa-09',
    genre: 'Coming of Age',
    text: 'Write the year you figured out that being liked and being known are different things.',
    difficulty: 'medium',
    tags: ['identity', 'friendship', 'loneliness'],
  },
  {
    id: 'coa-10',
    genre: 'Coming of Age',
    text: 'Someone returns to their hometown at 25 for the first time since leaving. Write what they notice.',
    difficulty: 'easy',
    tags: ['return', 'place', 'identity'],
  },
  {
    id: 'coa-11',
    genre: 'Coming of Age',
    text: 'Write a first heartbreak from the future — looking back from a distance of ten years.',
    difficulty: 'medium',
    tags: ['love', 'grief', 'time', 'retrospect'],
  },
  {
    id: 'coa-12',
    genre: 'Coming of Age',
    text: 'A mentor says something they don\'t realize will stay with someone for the rest of their life.',
    difficulty: 'easy',
    tags: ['mentorship', 'words', 'influence'],
  },
  {
    id: 'coa-13',
    genre: 'Coming of Age',
    text: 'Write the night someone decided to stop trying to be understood and started trying to understand.',
    difficulty: 'hard',
    tags: ['growth', 'empathy', 'turning point'],
  },
  {
    id: 'coa-14',
    genre: 'Coming of Age',
    text: 'A group of friends dissolves. Write the last time they were all together, before they knew it was the last time.',
    difficulty: 'medium',
    tags: ['friendship', 'endings', 'unawareness'],
  },
  {
    id: 'coa-15',
    genre: 'Coming of Age',
    text: 'Someone reads a book that breaks something open in them. Write what happens in the hour after they finish it.',
    difficulty: 'easy',
    tags: ['books', 'awakening', 'interior'],
  },

  // ─── HORROR (15) ─────────────────────────────────────────────────────────

  {
    id: 'hor-01',
    genre: 'Horror',
    text: 'Something in the house has always made that sound. Tonight you finally look.',
    difficulty: 'easy',
    tags: ['domestic', 'dread', 'uncanny'],
  },
  {
    id: 'hor-02',
    genre: 'Horror',
    text: 'Write a character who becomes gradually, politely certain that everyone around them has been replaced.',
    difficulty: 'medium',
    tags: ['paranoia', 'psychological', 'isolation'],
  },
  {
    id: 'hor-03',
    genre: 'Horror',
    text: 'A support group for people who all had the same dream. No one wants to be the first to describe it.',
    difficulty: 'medium',
    tags: ['collective', 'dread', 'dreams'],
  },
  {
    id: 'hor-04',
    genre: 'Horror',
    text: 'Write the last entry in a nature researcher\'s field journal. The handwriting changes on the final page.',
    difficulty: 'easy',
    tags: ['found document', 'wilderness', 'transformation'],
  },
  {
    id: 'hor-05',
    genre: 'Horror',
    text: 'Something has been following someone home every night for a year. They\'ve started to find it comforting.',
    difficulty: 'hard',
    tags: ['psychological', 'attachment', 'wrongness'],
  },
  {
    id: 'hor-06',
    genre: 'Horror',
    text: 'A town where everyone is extremely, insistently kind. Write the first person to notice.',
    difficulty: 'medium',
    tags: ['folk horror', 'community', 'wrongness'],
  },
  {
    id: 'hor-07',
    genre: 'Horror',
    text: 'Write a ghost story in which the ghost is completely unaware they\'re dead, and the horror is entirely the reader\'s.',
    difficulty: 'hard',
    tags: ['ghost', 'dramatic irony', 'quiet'],
  },
  {
    id: 'hor-08',
    genre: 'Horror',
    text: 'The photos from a family vacation all look wrong. No one else sees it.',
    difficulty: 'easy',
    tags: ['family', 'perception', 'gaslighting'],
  },
  {
    id: 'hor-09',
    genre: 'Horror',
    text: 'Write a children\'s story that slowly becomes something else entirely.',
    difficulty: 'hard',
    tags: ['form', 'subversion', 'escalation'],
  },
  {
    id: 'hor-10',
    genre: 'Horror',
    text: 'A new neighbor introduces themselves. Everything they say is technically correct and completely wrong.',
    difficulty: 'medium',
    tags: ['uncanny', 'suburban', 'dialogue'],
  },
  {
    id: 'hor-11',
    genre: 'Horror',
    text: 'Write the night before a procedure that is entirely routine and for some reason feels like a goodbye.',
    difficulty: 'medium',
    tags: ['dread', 'body', 'anticipation'],
  },
  {
    id: 'hor-12',
    genre: 'Horror',
    text: 'Someone moves into an apartment where the previous tenant left everything. Not because they were in a hurry.',
    difficulty: 'medium',
    tags: ['place', 'absence', 'objects'],
  },
  {
    id: 'hor-13',
    genre: 'Horror',
    text: 'Write a monster that doesn\'t want to be one.',
    difficulty: 'hard',
    tags: ['empathy', 'creature', 'interiority'],
  },
  {
    id: 'hor-14',
    genre: 'Horror',
    text: 'A road trip takes slightly longer than it should. Then a little longer than that.',
    difficulty: 'easy',
    tags: ['travel', 'time', 'disorientation'],
  },
  {
    id: 'hor-15',
    genre: 'Horror',
    text: 'Write the moment a character realizes the thing they\'ve been afraid of is not what they thought — and what they thought was actually worse.',
    difficulty: 'hard',
    tags: ['revelation', 'subversion', 'psychological'],
  },

  // ─── FANTASY (15) ────────────────────────────────────────────────────────

  {
    id: 'fan-01',
    genre: 'Fantasy',
    text: 'Write the first law of a magic system from the perspective of someone who broke it and survived.',
    difficulty: 'medium',
    tags: ['magic', 'rules', 'consequence'],
  },
  {
    id: 'fan-02',
    genre: 'Fantasy',
    text: 'A cartographer is hired to map a country that keeps changing while they draw it.',
    difficulty: 'medium',
    tags: ['place', 'change', 'obsession'],
  },
  {
    id: 'fan-03',
    genre: 'Fantasy',
    text: 'Write the deathbed confession of a retired villain. They\'re not particularly sorry.',
    difficulty: 'medium',
    tags: ['villain', 'voice', 'morality'],
  },
  {
    id: 'fan-04',
    genre: 'Fantasy',
    text: 'Two gods argue about something small. The argument has been going on for three hundred years.',
    difficulty: 'easy',
    tags: ['mythology', 'dialogue', 'scale'],
  },
  {
    id: 'fan-05',
    genre: 'Fantasy',
    text: 'Write the ordinary life of someone in a fantasy world — not the chosen one, not the knight. The baker. The clerk.',
    difficulty: 'easy',
    tags: ['worldbuilding', 'ordinary', 'perspective'],
  },
  {
    id: 'fan-06',
    genre: 'Fantasy',
    text: 'A prophecy is discovered to have a typo. Write the council meeting.',
    difficulty: 'easy',
    tags: ['humor', 'bureaucracy', 'subversion'],
  },
  {
    id: 'fan-07',
    genre: 'Fantasy',
    text: 'Write the last night of a war that lasted a century, from the perspective of someone who was born into it.',
    difficulty: 'hard',
    tags: ['war', 'generational', 'endings'],
  },
  {
    id: 'fan-08',
    genre: 'Fantasy',
    text: 'A dragon has lived long enough to watch everything it loved become myth.',
    difficulty: 'hard',
    tags: ['loss', 'time', 'perspective'],
  },
  {
    id: 'fan-09',
    genre: 'Fantasy',
    text: 'Write a heist in a world where lying is magically impossible.',
    difficulty: 'hard',
    tags: ['heist', 'constraint', 'creativity'],
  },
  {
    id: 'fan-10',
    genre: 'Fantasy',
    text: 'Someone is given the gift of seeing one true thing about every person they meet. They stop leaving their house.',
    difficulty: 'medium',
    tags: ['power', 'burden', 'isolation'],
  },
  {
    id: 'fan-11',
    genre: 'Fantasy',
    text: 'Write a fairy tale where the moral is genuinely ambiguous.',
    difficulty: 'hard',
    tags: ['fable', 'morality', 'form'],
  },
  {
    id: 'fan-12',
    genre: 'Fantasy',
    text: 'A kingdom where everyone forgets their dreams except one person, who remembers everyone\'s.',
    difficulty: 'medium',
    tags: ['dreams', 'burden', 'worldbuilding'],
  },
  {
    id: 'fan-13',
    genre: 'Fantasy',
    text: 'Write the interview process for a position that has only ever had one occupant — the last one died in the role.',
    difficulty: 'medium',
    tags: ['humor', 'dark', 'institution'],
  },
  {
    id: 'fan-14',
    genre: 'Fantasy',
    text: 'A paladin loses their faith on a Tuesday. Write the rest of the week.',
    difficulty: 'medium',
    tags: ['faith', 'identity', 'quiet'],
  },
  {
    id: 'fan-15',
    genre: 'Fantasy',
    text: 'Write the creation of a world from the perspective of something that didn\'t ask to be created.',
    difficulty: 'hard',
    tags: ['cosmology', 'voice', 'origin'],
  },

  // ─── SCI-FI (10) ─────────────────────────────────────────────────────────

  {
    id: 'sci-01',
    genre: 'Sci-Fi',
    text: 'A woman receives a message from a version of herself she doesn\'t remember being. The message is an apology.',
    difficulty: 'medium',
    tags: ['time', 'identity', 'regret'],
  },
  {
    id: 'sci-02',
    genre: 'Sci-Fi',
    text: 'Write the first generation born on a generation ship. They have never seen a planet and don\'t entirely believe in them.',
    difficulty: 'medium',
    tags: ['space', 'belief', 'generational'],
  },
  {
    id: 'sci-03',
    genre: 'Sci-Fi',
    text: 'In a world where memories can be archived and sold, write someone deciding which ones to keep.',
    difficulty: 'hard',
    tags: ['memory', 'technology', 'identity'],
  },
  {
    id: 'sci-04',
    genre: 'Sci-Fi',
    text: 'The last human who remembers the internet describes it to someone who was born after.',
    difficulty: 'easy',
    tags: ['nostalgia', 'technology', 'loss'],
  },
  {
    id: 'sci-05',
    genre: 'Sci-Fi',
    text: 'Write the retirement party for an AI that has been running continuously for forty years.',
    difficulty: 'medium',
    tags: ['AI', 'endings', 'humanity'],
  },
  {
    id: 'sci-06',
    genre: 'Sci-Fi',
    text: 'First contact has been made. Write the night before the announcement, from inside the room where people know.',
    difficulty: 'medium',
    tags: ['first contact', 'secrecy', 'anticipation'],
  },
  {
    id: 'sci-07',
    genre: 'Sci-Fi',
    text: 'A man has lived the same day 4,000 times. He\'s stopped trying to change it. Write today.',
    difficulty: 'hard',
    tags: ['time loop', 'resignation', 'interiority'],
  },
  {
    id: 'sci-08',
    genre: 'Sci-Fi',
    text: 'Write a near-future city through the eyes of someone who grew up in the version that came before.',
    difficulty: 'easy',
    tags: ['urban', 'change', 'nostalgia'],
  },
  {
    id: 'sci-09',
    genre: 'Sci-Fi',
    text: 'Terraforming is complete. Write the first rainfall on Mars. One person is there to see it.',
    difficulty: 'easy',
    tags: ['space', 'wonder', 'solitude'],
  },
  {
    id: 'sci-10',
    genre: 'Sci-Fi',
    text: 'A translation algorithm finally decodes a signal received 60 years ago. The message is very short and very strange.',
    difficulty: 'medium',
    tags: ['communication', 'mystery', 'revelation'],
  },

  // ─── ROMANCE (10) ────────────────────────────────────────────────────────

  {
    id: 'rom-01',
    genre: 'Romance',
    text: 'Two people who almost were something, years later, in the same room for the first time. Write only what goes unsaid.',
    difficulty: 'hard',
    tags: ['reunion', 'restraint', 'subtext'],
  },
  {
    id: 'rom-02',
    genre: 'Romance',
    text: 'Write a love story told entirely through the objects two people leave at each other\'s places.',
    difficulty: 'medium',
    tags: ['objects', 'accumulation', 'intimacy'],
  },
  {
    id: 'rom-03',
    genre: 'Romance',
    text: 'Someone falls in love with a person\'s handwriting before they meet them.',
    difficulty: 'easy',
    tags: ['letters', 'distance', 'longing'],
  },
  {
    id: 'rom-04',
    genre: 'Romance',
    text: 'Write the argument that finally says what two people have needed to say for three years.',
    difficulty: 'medium',
    tags: ['conflict', 'honesty', 'breakthrough'],
  },
  {
    id: 'rom-05',
    genre: 'Romance',
    text: 'Two people on a long flight. One of them already knows this is the last time they\'ll see the other.',
    difficulty: 'hard',
    tags: ['endings', 'restraint', 'travel'],
  },
  {
    id: 'rom-06',
    genre: 'Romance',
    text: 'Write a marriage proposal that goes wrong in a small, specific way — and still works.',
    difficulty: 'easy',
    tags: ['imperfection', 'vulnerability', 'humor'],
  },
  {
    id: 'rom-07',
    genre: 'Romance',
    text: 'Write the moment someone realizes they\'ve been in love for much longer than they thought.',
    difficulty: 'easy',
    tags: ['realization', 'retrospect', 'interiority'],
  },
  {
    id: 'rom-08',
    genre: 'Romance',
    text: 'Two people who are very good at being alone try to be good at being together. Write the first month.',
    difficulty: 'medium',
    tags: ['independence', 'adjustment', 'intimacy'],
  },
  {
    id: 'rom-09',
    genre: 'Romance',
    text: 'Write a breakup between two people who still love each other. No villain, no relief — just the thing itself.',
    difficulty: 'hard',
    tags: ['endings', 'loss', 'love'],
  },
  {
    id: 'rom-10',
    genre: 'Romance',
    text: 'Someone writes and deletes the same text message seventeen times. Write what they finally send.',
    difficulty: 'easy',
    tags: ['technology', 'vulnerability', 'decision'],
  },

  // ─── CRIME / NOIR (10) ───────────────────────────────────────────────────

  {
    id: 'noi-01',
    genre: 'Crime / Noir',
    text: 'Write the last night a detective believes in anything.',
    difficulty: 'medium',
    tags: ['disillusionment', 'voice', 'moral'],
  },
  {
    id: 'noi-02',
    genre: 'Crime / Noir',
    text: 'A witness to something small realizes they may be the only person who knows what really happened. They decide to stay quiet.',
    difficulty: 'medium',
    tags: ['conscience', 'complicity', 'choice'],
  },
  {
    id: 'noi-03',
    genre: 'Crime / Noir',
    text: 'Write a heist from the perspective of the person whose only job is to wait in the car.',
    difficulty: 'easy',
    tags: ['perspective', 'waiting', 'tension'],
  },
  {
    id: 'noi-04',
    genre: 'Crime / Noir',
    text: 'A con artist retires, moves to a small town, and starts to like it. Then someone from the old life shows up.',
    difficulty: 'medium',
    tags: ['identity', 'past', 'threat'],
  },
  {
    id: 'noi-05',
    genre: 'Crime / Noir',
    text: 'Write an interrogation scene in which the detective is the least honest person in the room.',
    difficulty: 'hard',
    tags: ['interrogation', 'unreliable', 'dialogue'],
  },
  {
    id: 'noi-06',
    genre: 'Crime / Noir',
    text: 'Someone inherits a storage unit from an uncle they barely knew. Write what they find, and what they do about it.',
    difficulty: 'easy',
    tags: ['discovery', 'family', 'decision'],
  },
  {
    id: 'noi-07',
    genre: 'Crime / Noir',
    text: 'Write the morning after a job gone wrong. Everyone got out. No one\'s talking.',
    difficulty: 'medium',
    tags: ['aftermath', 'silence', 'group'],
  },
  {
    id: 'noi-08',
    genre: 'Crime / Noir',
    text: 'A defense attorney wins a case they know they shouldn\'t have. Write the drive home.',
    difficulty: 'medium',
    tags: ['moral', 'victory', 'guilt'],
  },
  {
    id: 'noi-09',
    genre: 'Crime / Noir',
    text: 'Write a crime story with no crime in it — only the weight of one that hasn\'t happened yet.',
    difficulty: 'hard',
    tags: ['anticipation', 'tension', 'form'],
  },
  {
    id: 'noi-10',
    genre: 'Crime / Noir',
    text: 'Two people meet for coffee. Both of them are lying. Neither of them knows the other knows.',
    difficulty: 'medium',
    tags: ['dialogue', 'deception', 'tension'],
  },

  // ─── LITERARY / EXPERIMENTAL (10) ────────────────────────────────────────

  {
    id: 'lit-01',
    genre: 'Literary / Experimental',
    text: 'Write a story told entirely in the second person where \'you\' is clearly the wrong person.',
    difficulty: 'hard',
    tags: ['second person', 'form', 'voice'],
  },
  {
    id: 'lit-02',
    genre: 'Literary / Experimental',
    text: 'Write the same moment six times, from six different distances.',
    difficulty: 'hard',
    tags: ['perspective', 'repetition', 'form'],
  },
  {
    id: 'lit-03',
    genre: 'Literary / Experimental',
    text: 'Write a story in which nothing happens and everything changes.',
    difficulty: 'hard',
    tags: ['quiet', 'interiority', 'stillness'],
  },
  {
    id: 'lit-04',
    genre: 'Literary / Experimental',
    text: 'A character speaks to the reader directly, breaks the fourth wall, and then can\'t find their way back.',
    difficulty: 'hard',
    tags: ['metafiction', 'form', 'voice'],
  },
  {
    id: 'lit-05',
    genre: 'Literary / Experimental',
    text: 'Write a love letter to a place that no longer exists.',
    difficulty: 'medium',
    tags: ['place', 'loss', 'address'],
  },
  {
    id: 'lit-06',
    genre: 'Literary / Experimental',
    text: 'Write a story structured like a dictionary definition — with multiple entries that slowly become one story.',
    difficulty: 'hard',
    tags: ['form', 'structure', 'language'],
  },
  {
    id: 'lit-07',
    genre: 'Literary / Experimental',
    text: 'Write the same character at age 8, 18, 38, and 78. One paragraph each. No transitions.',
    difficulty: 'medium',
    tags: ['time', 'character', 'compression'],
  },
  {
    id: 'lit-08',
    genre: 'Literary / Experimental',
    text: 'Write a story in which the narrator keeps insisting something isn\'t important — and it is the most important thing.',
    difficulty: 'hard',
    tags: ['unreliable narrator', 'subtext', 'denial'],
  },
  {
    id: 'lit-09',
    genre: 'Literary / Experimental',
    text: 'Write an ending to a story we never read. Make us feel the weight of everything that came before.',
    difficulty: 'hard',
    tags: ['form', 'implication', 'ending'],
  },
  {
    id: 'lit-10',
    genre: 'Literary / Experimental',
    text: 'Write a story in which the setting is the protagonist.',
    difficulty: 'hard',
    tags: ['place', 'personification', 'form'],
  },

  // ─── HISTORICAL FICTION (8) ──────────────────────────────────────────────

  {
    id: 'his-01',
    genre: 'Historical Fiction',
    text: 'A soldier writes a letter home that he will never send. Write the letter and what he writes instead.',
    difficulty: 'medium',
    tags: ['war', 'letters', 'truth'],
  },
  {
    id: 'his-02',
    genre: 'Historical Fiction',
    text: 'Write the night before a voyage no one has made before, from the perspective of someone who isn\'t the captain.',
    difficulty: 'medium',
    tags: ['exploration', 'fear', 'ordinary'],
  },
  {
    id: 'his-03',
    genre: 'Historical Fiction',
    text: 'A woman in 1920 does something she\'s not supposed to. Write the specific logistics of how.',
    difficulty: 'medium',
    tags: ['agency', 'constraint', 'gender'],
  },
  {
    id: 'his-04',
    genre: 'Historical Fiction',
    text: 'Write the first day of something history remembers as inevitable, from inside the moment when it wasn\'t.',
    difficulty: 'hard',
    tags: ['history', 'irony', 'interiority'],
  },
  {
    id: 'his-05',
    genre: 'Historical Fiction',
    text: 'A translator at a peace negotiation realizes the two sides are not disagreeing about what they think.',
    difficulty: 'hard',
    tags: ['language', 'diplomacy', 'misunderstanding'],
  },
  {
    id: 'his-06',
    genre: 'Historical Fiction',
    text: 'Write a market day in a medieval city. No plague, no war, no prophecy. Just Tuesday.',
    difficulty: 'easy',
    tags: ['ordinary', 'worldbuilding', 'texture'],
  },
  {
    id: 'his-07',
    genre: 'Historical Fiction',
    text: 'Someone who lived through a revolution grows old in the world it made. They have complicated feelings.',
    difficulty: 'hard',
    tags: ['aftermath', 'aging', 'politics'],
  },
  {
    id: 'his-08',
    genre: 'Historical Fiction',
    text: 'Write a love story conducted entirely through objects passed between two people who cannot meet openly.',
    difficulty: 'medium',
    tags: ['constraint', 'love', 'objects'],
  },

  // ─── CHARACTER STUDIES (7) ───────────────────────────────────────────────

  {
    id: 'cha-01',
    genre: 'Character Studies',
    text: 'Write a character who is exactly who they say they are. Make it the most unsettling thing in the room.',
    difficulty: 'hard',
    tags: ['sincerity', 'uncanny', 'voice'],
  },
  {
    id: 'cha-02',
    genre: 'Character Studies',
    text: 'Write someone who is very funny and very sad — and knows it, and uses one to hide the other.',
    difficulty: 'medium',
    tags: ['humor', 'defense', 'interiority'],
  },
  {
    id: 'cha-03',
    genre: 'Character Studies',
    text: 'Write a character at their absolute best — competent, generous, clear. Then write what it costs them.',
    difficulty: 'hard',
    tags: ['competence', 'burden', 'contrast'],
  },
  {
    id: 'cha-04',
    genre: 'Character Studies',
    text: 'Write the internal logic of someone making a decision everyone else thinks is wrong.',
    difficulty: 'medium',
    tags: ['perspective', 'moral', 'interiority'],
  },
  {
    id: 'cha-05',
    genre: 'Character Studies',
    text: 'Write a person the morning after they did something they\'re proud of for the wrong reasons.',
    difficulty: 'hard',
    tags: ['moral complexity', 'pride', 'doubt'],
  },
  {
    id: 'cha-06',
    genre: 'Character Studies',
    text: 'Write someone who has never asked for help — the day they finally have to.',
    difficulty: 'medium',
    tags: ['pride', 'vulnerability', 'change'],
  },
  {
    id: 'cha-07',
    genre: 'Character Studies',
    text: 'Write a villain\'s ordinary Tuesday. No villainy. Just their life.',
    difficulty: 'medium',
    tags: ['humanizing', 'ordinary', 'moral'],
  },
];
